### PR TITLE
Created new hardware interface for switching between controller modes

### PR DESCRIPTION
**Pull request by davetcoleman**
This implements the "custom interface" described on this [wiki page](https://github.com/ros-controls/ros_control/wiki/control_mode) and addresses this issue https://github.com/ros-controls/ros_control/issues/99

### CODE REVIEW

**Comment by davetcoleman** [comment]
@adolfo-rt could you review this?

**Comment by adolfo-rt** [comment]
I have seen this PR, but I  can't really give an opinion yet, since I don't fully understand how the interface should be used (by controllers and the robot hardware abstraction) to change control modes at runtime (see comments on [related ros_controllers PR](https://github.com/ros-controls/ros_controllers/pull/62)).

So far I have the impression that static modes are well supported, but I'd like to know if the dynamic case should/will be supported, and how. I think this is a very good and attractive new feature, so we should take care that the most common usecases are well supported.

**Comment by davetcoleman** [comment]
The dynamic case is now supported. With my robot I can switch with these two calls:

switch to position mode

```
rosservice call /robot/controller_manager/switch_controller "{start_controllers: ['position_joint_mode_controller','left_position_trajectory_controller','right_position_trajectory_controller'], stop_controllers: ['velocity_joint_mode_controller','left_velocity_trajectory_controller','right_velocity_trajectory_controller'], strictness: 2}"
```

switch to velocity mode

```
rosservice call /robot/controller_manager/switch_controller "{start_controllers: ['velocity_joint_mode_controller','left_velocity_trajectory_controller','right_velocity_trajectory_controller'], stop_controllers: ['position_joint_mode_controller','left_position_trajectory_controller','right_position_trajectory_controller'], strictness: 2}"
```

**Comment by kphawkins** [comment]
So I'm not sure if I saw this when I wrote it, but I have an implementation which is very similar to this.  I have a set of files strewn out over my `gt-ros-pkg/universal_robot` repository (`hydro-devel-c-api` branch) which perform a very similar function.  They work natively with ros-control and do not require any direct modification, though more seamless integration would definitely help.

[`JointModeHandle`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_ctrl_client/include/ur_ctrl_client/joint_mode_iface.h)
[`SwitchModeController`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_controllers/include/ur_controllers/switch_mode_controller.h)
[Implementations of `SwitchModeController`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_controllers/include/ur_controllers/ur_switch_mode_controllers.h)

In addition, I have a Python helper class which allows one to easily switch joint controllers without having to always keep up with current/new joint modes.  This still needs work, but it is nice to only need to make a single call to the controller wanted running.  I see no reason why `ros-control` can't automatically determine controller/joint mode conflicts and stop them properly.

[`URControllerManager`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_py_utils/src/ur_py_utils/ur_controller_manager.py)
[It requires that each controller be assigned a mode parameter, seen here.](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_controllers/launch/load_default_controllers.launch)

I'm just leaving this here to help inform future discussion of a more official integration.

**Comment by adolfo-rt** [comment]
On these links:

> [`JointModeHandle`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_ctrl_client/include/ur_ctrl_client/joint_mode_iface.h)
> [`SwitchModeController`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_controllers/include/ur_controllers/switch_mode_controller.h)
> [Implementations of `SwitchModeController`](https://github.com/gt-ros-pkg/universal_robot/blob/hydro-devel-c-api/ur_controllers/include/ur_controllers/ur_switch_mode_controllers.h)

I like the fact that the handle type does not impose the available control modes, but is a general identifier (in your case an `int`). What is missing is a mapping between the identifiers and the actual hardware interfaces used by the controllers, which you are currently resolving with an additional mode setting in the controller configuration.

https://github.com/ros-controls/ros_controllers/pull/62 has comments that are relevant to this discussion.

**Comment by fmessmer** [comment]
#180 is the rebased version for indigo-devel

**Comment by davetcoleman** [comment]
pal-robotics has been putting a lot of work into improving this original PR - I believe this PR has been superseded by the hydro-devel branch of https://github.com/pal-robotics/ros_control

@bmagyar can you confirm?

@ipa-fxm I think your rebased version should be closed in favor of pal-robotics work. @adolfo-rt can you confirm this?

**Comment by bmagyar** [comment]
I do confirm.

**Pull request closed without merging**
