### PR TITLE
add urdf_geometry_parser to rosinstall file

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Should be cherry-picked to kinetic as well.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Not sure about adding `four_wheel_steering_msgs` in general.
We might move `four_wheel_steering_controller` into a separate repository though.

`ros_control` itself already  passes.
The other repos will hopefully pass after `xacro` was released.

**Comment by bmagyar** [comment]
Yes, we should discuss a bettre strategy for splitting the repos and also for test setups.
Is there a way to specify per-job rosinstall files with industrial_ci?

**Comment by bmagyar** [comment]
By the way, I've solved this issue for now by disabling the source-build of `ros_controllers` on the `ros_control` CI.

**Comment by mathias-luedtke** [comment]
> Is there a way to specify per-job rosinstall files with industrial_ci?

You could  specify another file in `ROSINSTALL_FILENAME`.
In additon there is distro-based lookup: If  `$ROSINSTALL_FILENAME.$ROSDISTRO` (e.g. `ros_control.rosinstall.melodic`)  exists, it it gets used instead of `$ROSINSTALL_FILENAME`.

**Comment by bmagyar** [comment]
The idea is that we could have a rosinstall with controllers and one
without.

**Pull request closed without merging**
