### PR TITLE
added C++11 flag

### PR DESCRIPTION
**Pull request by geoffviola**
I needed this change for lunar on Ubuntu 16.04

### CODE REVIEW

**Comment by bmagyar** [comment]
Wouldn't this remove functionality on platforms where gcc has C++14 support enabled by default? 
You could check if `CXX_STANDARD == 98` and only then set it `CMAKE_CXX_STANDARD 11`
https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

@ipa-mdl what do you think? Something like this could indeed help supporting compile-from-source on Ubuntu < 18.04.

**Comment by geoffviola** [comment]
I don't think it will remove the functionality. According to CMake "This property specifies the C++ standard whose features are requested to build this target". It's probably a good idea to test it anyway.

**Comment by mathias-luedtke** [comment]
I don't see the need to add this flag. We branched it out for melodic. `kinetic-devel` works perfectly fine on `lunar`.
If we really want to set this flag, I would set it to c++ 14 (ROS melodic default).

Please note, that setting flag leads to ABI breaks if mixed C++03 code.

**Comment by geoffviola** [comment]
Are you using Ubuntu 18.04? What version of GCC? C++14 was the default in GCC 6.1.

**Comment by mathias-luedtke** [comment]
> Please note, that setting the c++11 flag leads to ABI breaks with C++03 code.

I don't want to support the `melodic-devel` branch on `xenial` (or `trusty`).
(In accordance with [REP 3](http://www.ros.org/reps/rep-0003.html))

**Comment by mathias-luedtke** [comment]
@geoffviola: Why can't you switch to the `kinetic-deve` branch?
@bmagyar l think we should point out in the README that the master branch is meant for melodic only and that the `kinetic-devel` branch supports  `kinetic` and `lunar`.

**Comment by geoffviola** [comment]
Sorry, I thought it was not going to be backwards compatible. The kinetic branch seems like it would work better for me.

**Comment by bmagyar** [comment]
Thanks @ipa-mdl for pointing to `REP 3`, it makes it clear. 
@geoffviola , thanks for bringing up this point though, we'll update the readme with a note for Lunar.

**Pull request closed without merging**
