### PR TITLE
Introduce shared_ptr typedefs

### PR DESCRIPTION
**Pull request by bmagyar**
Not the final version, more of a WIP.
These changes shouldn't introduce changes to existing API or ABI, only extending API with the typedefs.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Looks more or less final to me. All public API is covered.
Only the transmission loader should get a typedef as well.

And `hwi_switch_test` should not use `boost::shared_ptr<Joint>` anymore.

**Comment by bmagyar** [comment]
So...I've turned it from a changeset affecting 10 files to one that affects 25. Now it looks quite final :) 
There were a lot of local typedefs especially `TransmissionPtr` repeated many times. There is a single typedef I left in there that is now not being used by any of our code but remains part of the public API, I've put a deprecation warning in comment there. I think we should remove that for Melodic.

**Review by mathias-luedtke — APPROVED** [review]
Great job!

**Comment by knorth55** [comment]
I have questions.
Is there a plan to backport this PR into `indigo-devel`?
Or is there any plan to merge this PR into `melodic-devel`?

**Comment by mathias-luedtke** [comment]
> Or is there any plan to merge this PR into melodic-devel?

It's still work in progess: #331 

> Is there a plan to backport this PR into indigo-devel?

:+1: 
@bmagyar:  Do you agree? I can prepare the PR.

**Comment by bmagyar** [comment]
Currently we are a bit stuck with this waiting for a pr of mine on
actionlib.

Yes it will go into melodic and kinetic too.

We could backport it into a last indigo release indeed. That'd ease
migration for all the folks still with indigo. If there's a volunteer
(wink-wink) I'd support it.

**Comment by mathias-luedtke** [comment]
@bmagyar: can't we cherry-pick this to melodic without the C++14 adaption for now? Just to keep the API compatible.

**Comment by bmagyar** [comment]
I agree. I'll try to fix it up tomorrow morning. If I remember well there's no C++14 there, only C++11 which if you enable it by hand can use in Kinetic too.

**Pull request merged**
