### PR TITLE
Initial release for a rqt controller manager plugin

### PR DESCRIPTION
**Pull request by kphawkins**
Allows users to unload/load/start/stop/view available controllers and view their name/state/type/hardware interface/resources.  No functionality yet exists for loading a controller from the parameter server or reloading libraries.

This is a preliminary release, I'm not sure if this works on other machines yet, but it seems to work smoothly on my own.  I'd like to see if interested parties would be like to test it and potentially prepare it for a hydro-devel merge.

### CODE REVIEW

**Comment by adolfo-rt** [comment]
This is **great**!. It does work on other machines :-). I see a table displaying stopped/running controllers along with their type, HW interface and resources. Right-clicking an entry allows you to stop,start and stop+unload a controller.

> No functionality yet exists for loading a controller from the parameter server or reloading libraries.

Does this fall within your plans?. It would be great to load controllers. Currently after unloading you can no longer reach a controller from the plugin. It should be possible to identify available controller configurations by doing something like:
- Allow to specify a namespace where controller configurations should live (defaults to /).
- Call the `namespace/controller_manager/list_controller_types` service to get all loadable plugin types.
- Search the specified namespace for parameters named `<string>/type`
- If `type` matches a loadable plugin type, then `<name>` is a controller that should be made available for loading.

A minor suggestion: How about renaming the 'Resources' column 'Claimed resources'?. Controllers that use read-only joint handles like the JointStateController show up as having no resources. They do use resources (all joints in this case), but claims none.

Know that you have an eager test subject and source of feedback here. Thanks again for your good work!.

**Comment by kphawkins** [comment]
Alright, I've added the load-controller functionality. Plus, it should support multiple controller managers running in separate namespaces.

**Comment by davetcoleman** [comment]
Great job!

**Comment by adolfo-rt** [comment]
I just had time to test the controller loading functionality, and it works as advertised :-). I consider this good enough for merging.

**Pull request merged**
