### PR TITLE
Use setuptools instead of distutils

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Use `setuptools` rather than `distutils`. See http://wiki.ros.org/noetic/Migration and ros/catkin#1048.

This PR also removes shebangs from `setup.py` files, since they should not be executed directly.

Note that it is not necessary to update all `package.xml` versions to 3, it is only required for packages containing `setup.py` files. But I updated them all for consistency.

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
hmm... Not sure why these `egg-info`s are being generated. Looking into it.

**Comment by bmagyar** [comment]
Is this something that we could also leverage in melodic?

**Comment by matthew-reynolds** [comment]
Yeah, in fact it should be cherry picked back to Kinetic as well, once the issues are resolved. https://github.com/ros/catkin/pull/1048 updated the recommended tool from Kinetic onwards.

Regarding the `egg-info` issue, this is being tracked upstream at https://github.com/ros/catkin/issues/1069.

**Comment by ahcorde** [comment]
Hi @matthew-reynolds and @bmagyar any updates here? These changes are need it for release the package in Noetic

**Comment by matthew-reynolds** [comment]
> any updates here?

Waiting on the upstream issue ros/catkin#1069. I just submitted a PR to address this (ros/catkin#1073), but I am not very well versed in the `catkin` codebase so I expect some discussion and iteration before that's resolved.

**Comment by matthew-reynolds** [comment]
Upstream PR merged into `noetic-devel` (ros/catkin#1073), just waiting on a backport to `kinetic-devel` now.

**Comment by matthew-reynolds** [comment]
Upstream backport is done. Waiting on next catkin release (https://github.com/ros/rosdistro/pull/24386). Once that is done, we can re-run this PR's tests, but only half of our tests will pass (the `ros-testing` ones) until the next Melodic sync.

**Comment by bmagyar** [comment]
Rebased to noetic and ready to merge when CI is happy

**Pull request merged**
