### PR TITLE
Don't export local include dirs

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
These are not local, but imported include directories.
You are are right, they should be removed.

In additon

```
LIBRARIES
    ${catkin_LIBRARIES}
    ${urdfdom_LIBRARIES}
```

is superfluous and should be removed as well.

However, I think `DEPENDS urdfdom` is needed to work as expected.
(This will implicitly add the include directories and libraries)

**Comment by jspricke** [comment]
@ipa-mdl sounds right, can you test it and open a separate pull request? I only needed this one ;).

**Comment by mathias-luedtke** [comment]
Let me put it this way: you must not remove  `${urdfdom_INCLUDE_DIRS}` from `INCLUDE_DIRS` without adding `DEPENDS urdfdom`.
The `urdfdom` headers must be exported for dependent packages to work (http://docs.ros.org/api/catkin/html/howto/format2/system_library_dependencies.html).
The current version emulates the `DEPENDS` behaviour and your patch breaks it.

> I only needed this one ;).

Why do you need it?

**Comment by jspricke** [comment]
Fixed, thanks!

I'm working on packaging ros-control for Debian:http://anonscm.debian.org/cgit/debian-science/packages/ros/ros-ros-control.git/

**Comment by jspricke** [comment]
See #230 for a Travis fix.

**Comment by mathias-luedtke** [comment]
I have tested your commit in indigo, it works.  Since `urdfdom` is a system dependency with no shared libray `DEPENDS urdfdom` is not crucial. But it will be necessary for custom installations, including debian ;)

Since you fixed the travis config for jade (thanks!), you could rebase this PR to actually use it.

**Comment by davetcoleman** [comment]
+1, @ipa-mdl does it look good to you now?

**Comment by mathias-luedtke** [comment]
It's fine now :)

**Pull request merged**
