### PR TITLE
Combined robot hw kinetic

### PR DESCRIPTION
**Pull request by toliver**
This PR has been reopen against kinetic-devel as suggested in https://github.com/ros-controls/ros_control/issues/234#issuecomment-217468209.

To see a description of the contents and the discussion history please have a look at #231 and #220.

### CODE REVIEW

**Comment by bmagyar** [comment]
@paulbovbel @mikepurvis @efernandez  isn't this interesting for you guys? 
@davetcoleman any thoughts?
Thanks Toni, I'll do some testing and get back here.

**Comment by davetcoleman** [comment]
LGTM +1

**Comment by bmagyar** [comment]
I've done several passes over it and played with the tests too, seems all good. I'm going to merge it now and quickly release for first Kinetic sync :+1:

**Comment by k-okada** [comment]
Hi @toliver, @bmagyar, @adolfo-rt .....

Since this patch, we can not compile `pr2_controller_manager` as reported at https://github.com/PR2/pr2_mechanism/issues/330
```
/home/yisha/workspace/gsoc/catkin_ws/src/pr2/pr2_mechanism/pr2_controller_manager/test/controllers/test_controller.cpp:131:61:   required from here
/opt/ros/kinetic/include/hardware_interface/internal/interface_manager.h:194:21: error: no matching function for call to ‘pr2_mechanism_model::RobotState::RobotState()’
         iface_combo = new T;
```
I'm not sure what is the root cause of this, but just want someone to confirm adding empty constructor is ok or not.
```
 class RobotState : public hardware_interface::HardwareInterface
  {
  public:
    /// constructor
 +  RobotState();
    RobotState(Robot *model);
```
c.f. https://github.com/k-okada/pr2_mechanism/commit/13af6b9f936295a748e99d7e866bd70bc103f1e0.

**Comment by mathias-luedtke** [comment]
Obviously, this PR introduced a break by requiring a default constructor.
At a first look there might be a way to remove this new requirement by extendeding the SFINAE workaround. I will try that and fix the warnings this PR introduced ;)

>  but just want someone to confirm adding empty constructor is ok or not.

All interfaces in `hardware_interface` come with a default constructor, but they check for this case of empty pointers and handle it. However, I don't see real need for them to have these (this depends on the actual RobotHW implementation).

In the case of your `RobotState` class I would consider a default constructor a problem, because `model_` is public. In order to have an empty constructor you should make in private, add a getter if needed and harden all ponter accesses.

**Comment by mikepurvis** [comment]
I finally gave this a shot in earnest, and couldn't believe how seamless it was. Big props to everyone involved for making it happen— really nice being able to compose a robot from RobotHW plugins using just a launch file and parameters. 👍

**Pull request merged**
