### PR TITLE
Added standalone rqt_controller_manager script

### PR DESCRIPTION
**Pull request by marcoesposito1988**

### CODE REVIEW

**Comment by davetcoleman** [comment]
Could you document somewhere how to launch this?

**Comment by marcoesposito1988** [comment]
You mean here in the pull request? I can't find any suitable place in the repo. Maybe in the wiki, but of course only after this is merged. 

This can be run with:
`rosrun rqt_controller_manager rqt_controller_manager`

It is a quite common use case actually: it is also documented at http://wiki.ros.org/rqt/UserGuide#Run_each_rqt_plugin_individually

**Comment by davetcoleman** [comment]
Could you add a section on the main wiki? http://wiki.ros.org/ros_control

Thanks!

**Comment by davetcoleman** [comment]
Also, this would be good to add to the indigo branch too

**Pull request merged**
