### PR TITLE
Implement transmission loading from URDF

### PR DESCRIPTION
**Pull request by adolfo-rt**
Refs #133.

### CODE REVIEW

**Comment by adolfo-rt** [comment]
All,

I don't want to merge this just now, because `gazebo_ros_control` needs to be updated simultaneously with a patch that is not yet ready. Still, while I get that done, I though I might lay here the ros_control part, which has been sitting around in my fork for quite some time now.

**Comment by davetcoleman** [comment]
Just saw this, awesome!

**Comment by davetcoleman** [comment]
Should this be targeted for the indigo branch?

**Comment by adolfo-rt** [comment]
It could very well be scheduled to land in Indigo. This would allow me to refactor some things in a cleaner way, and Indigo is just around the corner.

**Comment by adolfo-rt** [comment]
Superseded by #156. These changes will target indigo-devel.

**Pull request closed without merging**
