### PR TITLE
add minimum required pluginlib version

### PR DESCRIPTION
**Pull request by mikaelarguedas**
follow-up of https://github.com/ros-controls/ros_control/pull/315

For users trying to build this with an outdated pluginlib version

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
@ipa-mdl please merge if you agree.

**Review by mathias-luedtke — APPROVED** [review]

**Comment by mathias-luedtke** [comment]
> For users trying to build this with an outdated pluginlib version

@mikaelarguedas: if I am not mistaken the version is used by bloom/buildfarm only. How does this help users?

**Comment by mikaelarguedas** [comment]
> if I am not mistaken the version is used by bloom/buildfarm only. How does this help users?

catkin will generate a CMake warning if you find a build dependency that doesn't match the version constraints specified in the package.xml.

e.g. : 
```
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:213 (message):
  catkin_package() version mismatch: the package.xml of 'pluginlib'
  build_depends on 'class_loader >= 3.0.0', but 'class_loader 0.3.9' found
```

**Comment by mathias-luedtke** [comment]
I wasn't aware of that feature, thanks!

**Pull request merged**
