### PR TITLE
ros_control not building on the build farm

### PR DESCRIPTION
**Pull request by wjwwood**
In the last Hydro update it stated:

```
Packages Removed: 
ros-hydro-ros-control : 0.4.0
```

The ros_control packages are missing on the build farm:
http://www.ros.org/debbuild/hydro.html

I'm not sure why though?

### CODE REVIEW

**Comment by davetcoleman** [comment]
`transmission_interface` is still "failing to build on the farm" :/

what is wrong here?
https://github.com/ros-controls/ros_control/blob/94839805b1a8195d4a7213f7319aee18ca9dbf05/transmission_interface/CMakeLists.txt

Console output:
http://jenkins.willowgarage.com:8080/job/ros-hydro-transmission-interface_binarydeb_precise_i386/14/console

**Comment by wjwwood** [comment]
@davetcoleman you don't `find_package` `tinyxml` anywhere. Those variables `${tinyxml_*}` won't contain anything.

Also, you should `<build_depend>` and possibly `<run_depend>` on `tinyxml`.

**Comment by davetcoleman** [comment]
> Also, you should `<build_depend>` and possibly `<run_depend>` on `tinyxml`.

Tinyxml is not a ros package, so it should not be added to the package.xml, correct?

Fix attempted: https://github.com/ros/rosdistro/pull/1509

**Comment by wjwwood** [comment]
No. dependencies in a package.xml can be either system dependencies like tinyxml or Boost, or they can be catkin dependencies.

**Comment by wjwwood** [comment]
Looking into more, tinyxml "finding" is pretty fragile, even for rospack:

https://github.com/ros/rospack/blob/groovy-devel/CMakeLists.txt

I would just remove references to entirely from your CMakeLists.txt, with the exception of using its name directly in the `target_link_libraries(...)` call, like so:

```
target_link_libraries(${PROJECT_NAME}_parser ${catkin_LIBRARIES} ${tinyxml_LIBRARIES} tinyxml)
```

I think the real fix in this case is to add it to the package.xml so that it is installed. It is an older library which assumes that it can be found once installed by gcc and doesn't provide `find_package` and/or `pkg-config`.

**Comment by davetcoleman** [comment]
Third attempt:
https://github.com/ros/rosdistro/pull/1525

**Comment by davetcoleman** [comment]
Failed again:
http://jenkins.willowgarage.com:8080/job/ros-hydro-transmission-interface_binarydeb_precise_amd64/16/console

**Comment by wjwwood** [comment]
converted to a pull request

**Comment by davetcoleman** [comment]
I have confirmed it builds.

**Comment by davetcoleman** [comment]
Eventually it'll work: https://github.com/ros/rosdistro/pull/1529

**Comment by mikeferguson** [comment]
@davetcoleman @wjwwood Given how much trouble you had with this, would it be worthwile to add this to either the Groovy or Hydro migration pages (whichever release it was converted to an upstream/system dependency)?

**Comment by davetcoleman** [comment]
It built finally!

TinyXml was actually converted to a upstream/system dependency in Electric, but rosbuild had some magic scripts in the background that took care of it. I already updated the [tinyxml wiki](www.ros.org/wiki/tinyxml) but I imagine a link could be added to the Groovy migration page.

**Comment by davetcoleman** [comment]
I've added a link to both the Hydro and Groovy migration pages.

**Pull request merged**
