### PR TITLE
Joint limits interface

### PR DESCRIPTION
**Pull request by adolfo-rt**
### URDF-agnostic joint limits specification
- **Joint limits** Position, velocity, acceleration, jerk and effort.
- **Soft joint limits** Soft position limits, k_p, k_v (as described [here](http://www.ros.org/wiki/pr2_controller_manager/safety_limits)).
- Utility method for loading **joint limits** information from **URDF** (only position, velocity, effort)
- Utility method for loading **soft joint limits** information from **URDF**
- Utility method for loading **joint limits** from **ROS parameter server** (all values). Parameter specification is the same used in MoveIt, with the addition that we also parse jerk and effort limits.

**Note** Joint limits specification should maybe live outside ros_control. I don't like that there's some code duplication between this pull request and MoveIt.

**Note** Maybe utilities for loading values should live elsewhere, to not impose the URDF dependency, or make it optional. For now it's required.
### Joint limits interface
- _ros_control_ interface for enforcing joint limits.
- For _effort-controlled_ joints, the soft-limits implementation from the PR2 has been ported.
- For _position-controlled_ joints, a modified version of the PR2 soft limits has been implemented.
- For _velocity-controlled_ joints, simple saturation based on acceleration and velocity limits has been implemented.

**Note** Joint limits enforcing for effort-controlled joints has **not yet** been unit tested. Position- and velocity-controlled joint cases do have tests in place.
### Example

``` c++
using namespace joint_limits_interface;

// Populate joint limits from URDF
UrdfJointConstPtr urdf_joint = urdf_->getJoint(name);
JointLimits limits;
SoftJointLimits soft_limits;
const bool limits_ok = getJointLimits(urdf_joint, limits) && getSoftJointLimits(urdf_joint, soft_limits);

// Register handle for enforcing limits of a position-controlled joint
JointHandle joint_handle; // Populate values...
PositionJointSoftLimitsInterface limits_iface_;
if (limits_ok)
{
  PositionJointSoftLimitsHandle handle(joint_handle, // We read the state and read/write the command
                                       limits,       // Limits spec
                                       soft_limits)  // Soft limits spec
  limits_iface_.registerHandle(handle);
}

// Populate with other handles...

// Enforce joint limits
ros::Duration period(0.001); // Control period
limits_iface_.enforceLimits(period); // Apply to all registered handles

// One can also enforce limits on a per-handle basis
limits_iface_.getHandle(joint_handle.getName()).enforceLimits(period);
```

### CODE REVIEW

**Comment by wmeeusse** [comment]
Nice work! One question: when writing a controller, would you have to decide if your controller requests a PositionJointSoftLimitsInterface or a regular PositionJointInterface?

**Comment by adolfo-rt** [comment]
> Nice work! One question: when writing a controller, would you have to decide if your controller requests a PositionJointSoftLimitsInterface or a regular PositionJointInterface? 

 I did not make this clear in the example, sorry.

The interface is not a `HardwareInterface`, hence is not meant to be used by controllers. Controllers would request a `PositionJointInterface`, regardless of whether limits enforcing is in place or not.

The `JointLimitsInterface` is meant to be in the `write()` method of your robot abstraction (in the same spirit of the `TransmissionInterface`).This is more or less how I use it now:

``` c++
void MyRobot::write(ros::Time time, ros::Duration period)
{
  jnt_limits_interface_.enforceLimits(period); // Enforce limits
  jnt_to_act_pos_cmd_.propagate();             // Propagate transmissions
  // send command to actual hardware
}
```

Enforcing limits actually **overwrites** the commands set by the controllers, it does not operate on a separate data buffer, so you can add/remove that line of code without having to propagate changes elsewhere. In fact, adding joint limits enforcing to one of our robots was pretty minimal: 20 sloc for setting up the interface (reading limits from URDF, registering handles), 1 sloc for actually enforcing limits, and <10 sloc in include statements, class members, etc.

**Comment by wmeeusse** [comment]
Thanks for the clarification, now the example makes a lot more sense ;-)   I'd love to see this merged in.

**Comment by adolfo-rt** [comment]
@wmeeusse, @jbohren, @davetcoleman. I'd be interested in merging this into hydro-devel as well, but I don't have catkin workspace setup. It would be great if one of you has extra cycles to build and run the tests of ros_control on a catkin system just to make sure that I didn't mess up the `package.xml` scripts.

**Comment by davetcoleman** [comment]
Nice work! I'm afraid I'm pretty busy at the moment...

**Comment by davetcoleman** [comment]
Other thoughts: I think abstracting the URDF dependency is unnecessary work and complexity - ROS uses URDF (and future versions of it) and this project is called **ros**_control 

Also, I slightly modified and moved your above documentation to [ros_control on the ros.org wiki](http://ros.org/wiki/ros_control#Joint_Limits)

**Comment by adolfo-rt** [comment]
@davetcoleman I agree with your statement about ros and URDF. The compromise I ended up with was not exposing URDF internals like `urdf::Joint` in the handle and interface classes, but rather have a separate set of convenience methods for populating limits data from URDF.

This is meaningful even if ros _currently_ uses URDF, because if in the future ros moves to RML or something else, we only need to write a new set of convenience methods, and not break the API of the actual interface.

**Comment by adolfo-rt** [comment]
Also, thanks @davetcoleman for updating the ros wiki. I'm planning on moving the example to the ros_control wiki, for consistency with the other interfaces. I just didn't have time to do it yesterday.

**Comment by davetcoleman** [comment]
I can confirm the joint_limits_interface builds successfully in catkin

**Comment by adolfo-rt** [comment]
Thanks Dave.

**Pull request merged**
