### PR TITLE
Rebased  #148 (Added pos+vel and pos+vel+acc command interfaces)

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Rebased #148 to indigo-devel
It compiles, but I haven't tested it yet.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
CI fails because of  #170

**Comment by adolfo-rt** [comment]
Great!, thanks for rebasing on indigo.

> It compiles, but I haven't tested it yet.

Is the test suite at least passing?, you only have to make the `test` target.

> CI fails because of #170

Travis CI does not yet support 14.04, so there is currently no straightforward mechanism to validate pull requests on indigo.

**Comment by mathias-luedtke** [comment]
catkin_make test:
The following tests FAILED:
         21 - _ctest_joint_limits_interface_gtest_joint_limits_interface_test (Failed)
         22 - _ctest_joint_limits_interface_gtest_joint_limits_urdf_test (Failed)
         23 - _ctest_joint_limits_interface_rostest_test_joint_limits_rosparam.test (Failed)
         27 - _ctest_transmission_interface_gtest_simple_transmission_test (Failed)
         28 - _ctest_transmission_interface_gtest_differential_transmission_test (Failed)
         29 - _ctest_transmission_interface_gtest_four_bar_linkage_transmission_test (Failed)
         30 - _ctest_transmission_interface_gtest_transmission_interface_test (Failed)
         31 - _ctest_transmission_interface_gtest_transmission_parser_test (Failed)
         32 - _ctest_transmission_interface_gtest_simple_transmission_loader_test (Failed)
         33 - _ctest_transmission_interface_gtest_differential_transmission_loader_test (Failed)
         34 - _ctest_transmission_interface_gtest_four_bar_linkage_transmission_loader_test (Failed)
         35 - _ctest_transmission_interface_gtest_transmission_interface_loader_test (Failed)
         36 - _ctest_diff_drive_controller_rostest_test_diff_drive_controller.test (Failed)
         37 - _ctest_diff_drive_controller_rostest_test_diff_drive_controller_limits.test (Failed)
         38 - _ctest_diff_drive_controller_rostest_test_diff_drive_timeout.test (Failed)
         39 - _ctest_diff_drive_controller_rostest_test_diff_drive_multipliers.test (Failed)
         40 - _ctest_diff_drive_controller_rostest_test_diff_drive_wrong.test (Failed)
         41 - _ctest_diff_drive_controller_rostest_test_diff_drive_bad_urdf.test (Failed)
         42 - _ctest_diff_drive_controller_rostest_test_diff_drive_odom_tf.test (Failed)
         43 - _ctest_joint_trajectory_controller_gtest_quintic_spline_segment_test (Failed)
         44 - _ctest_joint_trajectory_controller_gtest_trajectory_interface_test (Failed)
         45 - _ctest_joint_trajectory_controller_gtest_joint_trajectory_segment_test (Failed)
         46 - _ctest_joint_trajectory_controller_gtest_joint_trajectory_msg_utils_test (Failed)
         47 - _ctest_joint_trajectory_controller_gtest_init_joint_trajectory_test (Failed)
         48 - _ctest_joint_trajectory_controller_rostest_test_tolerances.test (Failed)
         49 - _ctest_joint_trajectory_controller_rostest_test_joint_trajectory_controller.test (Failed)

**Comment by adolfo-rt** [comment]
It could be that not all tests are built. If you run `make tests` (plural), does it build something else?.

Those tests should pass. I was wondering about the tests of the current PR.

**Comment by mathias-luedtke** [comment]
catkin_make tests followed by catkin_make test gives: 100% tests passed, 0 tests failed out of 40 :)

**Comment by adolfo-rt** [comment]
OK then, so I consider this good to merge. Not that for this to become useful, some controllers must be made aware of this new interface. There was https://github.com/ros-controls/ros_controllers/pull/83, that can be revived for the `joint_trajectory_controller`.

Future improvements would include making joint limits enforcing and transmissions aware of these new hardware interfaces. These can be added later on as usecases arise.

**Pull request merged**
