### PR TITLE
Removed the local FindTINYXML.cmake and switched to catkin's cmake_modules version

### PR DESCRIPTION
**Pull request by davetcoleman**
For https://github.com/ros/cmake_modules/issues/4

### CODE REVIEW

**Comment by wjwwood** [comment]
You should export TinyXML as a `DEPENDS`, since you use it in your headers:

https://github.com/ros-controls/ros_control/blob/0c8e0593d60fd6b75538fd50956e0c149b7858fb/transmission_interface/include/transmission_interface/transmission_info.h#L48

Which you install. You can do that like this:

``` cmake
catkin_package(
...
  DEPENDS
    TinyXML
)
```

**Comment by davetcoleman** [comment]
Thanks William!

**Comment by adolfo-rt** [comment]
+1!

**Comment by kphawkins** [comment]
Can we maybe put a link to cmake_modules somewhere so that it's clear that this is a necessary package now? (https://github.com/ros/cmake_modules)  Possibly in the README or changelogs?  There's no .deb yet, I assume.

**Comment by davetcoleman** [comment]
Its already been released to public debians for Groovy and Hydro, and the install from source method will install it automatically from rosdep assuming you run that command again.

Updated [CHANGELOG](https://github.com/ros-controls/ros_control/blob/hydro-devel/transmission_interface/CHANGELOG.rst)

**Comment by wjwwood** [comment]
It is actually only in shadow fixed at the moment, but it will be available in the public debs on the next sync. In the mean time you would only need to download it into your workspace, building it from source is really easy if you are already building other things from source.

**Pull request merged**
