### PR TITLE
export dll on Windows

### PR DESCRIPTION
**Pull request by kejxu**
`.so` are exported on Linux using `LIBRARY` property, but `.dll` needs to use `RUNTIME`. to fix this, we could remove the `LIBRARY` specification, and export all the output to `package_lib`, so library and runtime are all exported

or we could add `RUNTIME DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}`

same change as in https://github.com/ros-controls/realtime_tools/pull/33

### CODE REVIEW

**Review by mathias-luedtke — CHANGES_REQUESTED** [review]
Our `CMakeLists.txt` follows the [recommendations](http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html#installing).
I don't know what implications the change would have.

**Comment by traversaro** [comment]
> or we could add RUNTIME DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}

Just a small question: the CMake documentation recommends to install `RUNTIME` library targets in the `bin` subdirectory of the install folder (see https://cmake.org/cmake/help/v3.13/manual/cmake-packages.7.html) and the vcpkg package manager from Microsoft actually rejects with a check packages that place their `.dll` files in the `lib` folder (see https://github.com/Microsoft/vcpkg/blob/5ff5ab7ae29313e95eab07172721800c5fa84c0c/toolsrc/src/vcpkg/postbuildlint.cpp#L206).
This convention is used in most existing C++ libraries, see for example OpenCV (https://github.com/opencv/opencv/blob/8f4e5c2fb8d473c69a3b14983583332738d33372/cmake/OpenCVModule.cmake#L1001) or the gazebo-related ignition libraries developed by Open Robotics (see https://bitbucket.org/ignitionrobotics/ign-cmake/src/3629811d05b872b3d98f1937694984b9a6cc600e/cmake/IgnUtils.cmake#lines-1260).

There is any reason for not following a relatively well established convention and installing `.dll` files in `lib` folder instead?

**Comment by traversaro** [comment]
Actually I noticed that `catkin` documentation itself seems to recommend to install RUNTIME libraries in the `${CATKIN_GLOBAL_BIN_DESTINATION}` location:  http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html

**Comment by mathias-luedtke** [comment]
If it helps, we can extend it to
```
install(TARGETS ${PROJECT_NAME}
        ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION})
```

But not 
 > or we could add RUNTIME DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}

**Comment by seanyen** [comment]
> There is any reason for not following a relatively well established convention and installing .dll files in lib folder instead?

@traversaro For those changes in ros-controls, I think it doesn't hurt to follow the guidance to place them to ${CATKIN_GLOBAL_BIN_DESTINATION}. However, JFYI, I noticed in some packages (not in this case), they create shared libs as plugins and the plugin location managed by plugin.xml expect them to be under ${CATKIN_PACKAGE_LIB_DESTINATION}. (One example, https://github.com/PickNikRobotics/rviz_visual_tools/blob/melodic-devel/plugin_description.xml)

**Comment by kejxu** [comment]
> > There is any reason for not following a relatively well established convention and installing .dll files in lib folder instead?
> 
> @traversaro For those changes in ros-controls, I think it doesn't hurt to follow the guidance to place them to ${CATKIN_GLOBAL_BIN_DESTINATION}. However, JFYI, I noticed in some packages (not in this case), they create shared libs as plugins and the plugin location managed by plugin.xml expect them to be under ${CATKIN_PACKAGE_LIB_DESTINATION}.

Thanks for helping out and elaborate on this Sean! @traversaro and @ipa-mdl, [this](https://github.com/PickNikRobotics/rviz_visual_tools/blob/melodic-devel/plugin_description.xml) is an example Sean showed to me earlier, maybe you'd also find it helpful =)

**Comment by traversaro** [comment]
Thanks for the answers @seanyen-msft and @kejxu !

> However, JFYI, I noticed in some packages (not in this case), they create shared libs as plugins and the plugin location managed by plugin.xml expect them to be under ${CATKIN_PACKAGE_LIB_DESTINATION}. (One example, https://github.com/PickNikRobotics/rviz_visual_tools/blob/melodic-devel/plugin_description.xml)

I tried to understand ***why*** the plugin needs to be located in `<prefix>/lib`, and I found the core reason is the following `plugin`'s lib function:
https://github.com/ros/pluginlib/blob/0a3c0de442596b46026eb4c738130bce90421927/pluginlib/include/pluginlib/class_loader_imp.hpp#L302
in which the directories in which plugins are searched are just obtained by adding `/lib` to each path contained in the `CMAKE_PREFIX_PATH` .

Interestingly, in the ROS2's branch, the equivalent function has been modified to search also in the `<prefix>/bin` directories,  see this PR: https://github.com/ros/pluginlib/pull/97 . 

I noticed that in the ROSOnWindows's fork of `pluginlib`, an equivalent change has been committed in https://github.com/ms-iot/pluginlib/pull/7 . So, as far as I understand now it should be ok to install `.dll` to `/bin` in all cases, (even in https://github.com/PickNikRobotics/rviz_visual_tools/blob/melodic-devel/plugin_description.xml) thanks to the fix provided in https://github.com/ms-iot/pluginlib/pull/7 , but perhaps I am missing something.

**Comment by seanyen** [comment]
> Interestingly, in the ROS2's branch, the equivalent function has been modified to search also in the <prefix>/bin directories, see this PR: ros/pluginlib#97 .

@traversaro thanks to point out this change! Sounds like we are converging to some similar logic.

(Sorry for hijacking this PR for discussion) @wjwwood as @traversaro pointed out, it looks like in ROS2 you are also hitting the problem that placing plugin DLL to global path won't be searched by plugin loader on Windows. Since both of our solutions are similar (ms-iot/pluginlib#7), as we move forward, are we safe to say that now the general guidance for Windows (for both ROS1 and ROS2) are like:
* For executables, ROS recommends to place them under ${CATKIN_PACKAGE_BIN_DESTINATION}. [ref](http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_executables.html)
* For DLL, ROS recommends to place them under ${CATKIN_GLOBAL_BIN_DESTINATION}, **no matter it is a plugin or just a regular shared library**. [ref](http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html)

**Comment by wjwwood** [comment]
In ROS 2, there's no `CATKIN_*` variables. See rviz for an example with both shared libraries and plugins:

- https://github.com/ros2/rviz/blob/a8eea3365c743afb8f38470b9697a58484c2c764/rviz_default_plugins/CMakeLists.txt#L265-L272

Pluginlib was modified in ROS 2 to search in `bin` as well as `lib`:

- https://github.com/ros/pluginlib/blob/36d4128fb2995ca6759268cf19978e65b39eefc3/pluginlib/include/pluginlib/class_loader_imp.hpp#L420

**Comment by bmagyar** [comment]
I appreciate you working on this and bringing `ros_control` to more users however I would be reluctant to claim Windows support until we have some sort of CI backing it up. I have no time or instruments to test anything on Windows, without a CI to help out we may keep breaking platform compatibility.

Do you have anything in store for that?

**Comment by kejxu** [comment]
> I appreciate you working on this and bringing `ros_control` to more users...

thanks for the input! before answer the CI question, here is a bit more justification to this pull request =)

this change and https://github.com/ros-controls/realtime_tools/pull/33 are, as @ipa-mdl and @traversaro mentioned (thanks!), just minor fine-tuning following [catkin recommendation](http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html#installing). This change is needed so that runtime binaries would be exported on Windows (`RUNTIME` needs to be specified)

> ...however I would be reluctant to claim Windows support until we have some sort of CI backing it up. I have no time or instruments to test anything on Windows, without a CI to help out we may keep breaking platform compatibility.
> 
> Do you have anything in store for that?

as for Windows hosting (CI), at this point we are hosting a daily Windows build for major ROS distributions, which includes [desktop_full](https://ros-win.visualstudio.com/ros-win/_build?definitionId=19). This build currently retrieves source from `ms-iot:init_windows`, yet we will soon deploy another pipeline for `ros-controls:melodic-devel` =)

at the same time, an Azure Pipelines based CI for PR is on our planning, and we will start working on that once the bandwidth allows.

**Review by mathias-luedtke — APPROVED** [review]
The is safe to merge :)

**Pull request merged**
