### PR TITLE
Fixed claim policy for actuator command interface

### PR DESCRIPTION
**Pull request by nlamprian**
I believe the actuator command interface should claim the resources.

### CODE REVIEW

**Review by mathias-luedtke — APPROVED** [review]
Should be cherry-picked to jade/kinetic as well.

**Comment by bmagyar** [comment]
Hiya,
Could you please put this in a bit more context? Have you encountered an issue arising from this?

**Comment by nlamprian** [comment]
I haven't actually used the interface. I just noticed this as I was examining the repo. ActuatorCommand is the only read-write interface that does not claim its resources.

**Comment by bmagyar** [comment]
Hi @pAIgn10 ,

I would prefer to not to touch the core `ros_control` libraries for Indigo anymore. Jade is almost EOL. Could you please reopen this PR against kinetic-devel?

**Comment by nlamprian** [comment]
@bmagyar, done. Not sure what exactly happened with this change. Please let me know if you need me to take any more actions.

**Comment by bmagyar** [comment]
...and could you please rebase it too? The PR looks messy with comments from old commits as the redirecting of the PR pulled those in.

**Review by bmagyar — CHANGES_REQUESTED** [review]
Rebase or cherry-pick on kinetic-devel needed

**Comment by nlamprian** [comment]
I find it easiest to cherry-pick the commit and open a new PR on kinetic-devel.

**Comment by bmagyar** [comment]
That'd be equally good :+1:

**Pull request closed without merging**
