### PR TITLE
catkinizing, could still be cleaned up

### PR DESCRIPTION
**Pull request by jbohren**
Not ready to merge yet, but might as well post it here so people don't duplicate work.

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1

**Comment by jbohren** [comment]
This now has a hybrid buildsystem, so it can be built in catkin and rosbuild workspaces. The only things missing are cmake install commands so it can be released with bloom.

**Comment by jbohren** [comment]
Sorry, I thought I had left these in. That's just an oversight.

**Comment by adolfo-rt** [comment]
No problem, I'll put them back in.

**Pull request merged**
