### PR TITLE
Throw error if EffortJointSaturationHandle is missing effort or velocity limits

### PR DESCRIPTION
**Pull request by davetcoleman**
This makes the EffortJointSaturationHandle have uniform behavior with all the other SaturationHandles.  It also makes it behave the same as the EffortJointSoftLimitsHandle, where it has:

```
   EffortJointSoftLimitsHandle(const hardware_interface::JointHandle& jh,
                               const JointLimits&                     limits,
                               const SoftJointLimits&                 soft_limits)
   : jh_(jh),
     limits_(limits),
     soft_limits_(soft_limits)
   {
     if (!limits.has_velocity_limits)
     {
       throw JointLimitsInterfaceException("Cannot enforce limits for joint '" + getName() +
                                            "'. It has no velocity limits specification.");
     }
     if (!limits.has_effort_limits)
     {
       throw JointLimitsInterfaceException("Cannot enforce limits for joint '" + getName() +
                                            "'. It has no effort limits specification.");
     }
   }
```

See this discussion for more details https://github.com/ros-controls/ros_control/issues/213

### CODE REVIEW

**Comment by efernandez** [comment]
:+1: 

Re-started the test job. I was failing on a `rosdep` dependency, completely unrelated with this PR.

**Comment by efernandez** [comment]
@adolfo-rt Do you want to add something here? It looks you're OK with this, as I see on #213 discussion.

**Comment by bmagyar** [comment]
I think this is something we should push to Lunar or maybe even consider for Kinetic. 
I could cherry-pick these changes to either or both.

Opinions? 
@davetcoleman  @efernandez  @ipa-mdl @ipa-fxm @miguelprada

**Comment by efernandez** [comment]
LGTM

**Comment by davetcoleman** [comment]
+1 @bmagyar to cherry-picking to Kinetic

**Comment by efernandez** [comment]
:+1: for merging so it gets into `lunar`.

Re. cherry-picking to `kinetic`, I'm afraid that it could impact someone already relying on the previous behavior, either intentionally or not.

**Comment by davetcoleman** [comment]
I think if anything, this improves the safety of robots and is a bug fix. The only changes someone might see is that their controller might throw an exception at *startup* because no limits were specified. This is better than misleading a user into thinking limits are being checked for, when they are actually not.

I've just changed it to target kinetic, since we haven't branched for lunar and I don't think its time yet for that.

**Comment by efernandez** [comment]
Fair enough

**Review by bmagyar — APPROVED** [review]
Thanks for the discussion guys.

**Pull request merged**
